<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class OrderGoodsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('order_goods')->insert(
            [
                [
                    'goods_id' => rand(1,10),
                    'goods_sku' => 'GS' . substr(md5(time()), 0, 8) . rand(100,999),
                    'order_id' => rand(1, 20),
                    'number' => rand(1, 10),
                    'json' => '{}',
                    'create_time' => strtotime('-10 day') + rand(86400, 864000),
                    'update_time' => strtotime('-10 day') + rand(86400, 864000),
                ],[
                    'goods_id' => rand(1,10),
                    'goods_sku' => 'GS' . substr(md5(time()), 0, 8) . rand(100,999),
                    'order_id' => rand(1, 20),
                    'number' => rand(1, 10),
                    'json' => '{}',
                    'create_time' => strtotime('-10 day') + rand(86400, 864000),
                    'update_time' => strtotime('-10 day') + rand(86400, 864000),
                ],[
                    'goods_id' => rand(1,10),
                    'goods_sku' => 'GS' . substr(md5(time()), 0, 8) . rand(100,999),
                    'order_id' => rand(1, 20),
                    'number' => rand(1, 10),
                    'json' => '{}',
                    'create_time' => strtotime('-10 day') + rand(86400, 864000),
                    'update_time' => strtotime('-10 day') + rand(86400, 864000),
                ],[
                    'goods_id' => rand(1,10),
                    'goods_sku' => 'GS' . substr(md5(time()), 0, 8) . rand(100,999),
                    'order_id' => rand(1, 20),
                    'number' => rand(1, 10),
                    'json' => '{}',
                    'create_time' => strtotime('-10 day') + rand(86400, 864000),
                    'update_time' => strtotime('-10 day') + rand(86400, 864000),
                ],[
                    'goods_id' => rand(1,10),
                    'goods_sku' => 'GS' . substr(md5(time()), 0, 8) . rand(100,999),
                    'order_id' => rand(1, 20),
                    'number' => rand(1, 10),
                    'json' => '{}',
                    'create_time' => strtotime('-10 day') + rand(86400, 864000),
                    'update_time' => strtotime('-10 day') + rand(86400, 864000),
                ],[
                    'goods_id' => rand(1,10),
                    'goods_sku' => 'GS' . substr(md5(time()), 0, 8) . rand(100,999),
                    'order_id' => rand(1, 20),
                    'number' => rand(1, 10),
                    'json' => '{}',
                    'create_time' => strtotime('-10 day') + rand(86400, 864000),
                    'update_time' => strtotime('-10 day') + rand(86400, 864000),
                ],[
                    'goods_id' => rand(1,10),
                    'goods_sku' => 'GS' . substr(md5(time()), 0, 8) . rand(100,999),
                    'order_id' => rand(1, 20),
                    'number' => rand(1, 10),
                    'json' => '{}',
                    'create_time' => strtotime('-10 day') + rand(86400, 864000),
                    'update_time' => strtotime('-10 day') + rand(86400, 864000),
                ],[
                    'goods_id' => rand(1,10),
                    'goods_sku' => 'GS' . substr(md5(time()), 0, 8) . rand(100,999),
                    'order_id' => rand(1, 20),
                    'number' => rand(1, 10),
                    'json' => '{}',
                    'create_time' => strtotime('-10 day') + rand(86400, 864000),
                    'update_time' => strtotime('-10 day') + rand(86400, 864000),
                ],[
                    'goods_id' => rand(1,10),
                    'goods_sku' => 'GS' . substr(md5(time()), 0, 8) . rand(100,999),
                    'order_id' => rand(1, 20),
                    'number' => rand(1, 10),
                    'json' => '{}',
                    'create_time' => strtotime('-10 day') + rand(86400, 864000),
                    'update_time' => strtotime('-10 day') + rand(86400, 864000),
                ],[
                    'goods_id' => rand(1,10),
                    'goods_sku' => 'GS' . substr(md5(time()), 0, 8) . rand(100,999),
                    'order_id' => rand(1, 20),
                    'number' => rand(1, 10),
                    'json' => '{}',
                    'create_time' => strtotime('-10 day') + rand(86400, 864000),
                    'update_time' => strtotime('-10 day') + rand(86400, 864000),
                ],[
                    'goods_id' => rand(1,10),
                    'goods_sku' => 'GS' . substr(md5(time()), 0, 8) . rand(100,999),
                    'order_id' => rand(1, 20),
                    'number' => rand(1, 10),
                    'json' => '{}',
                    'create_time' => strtotime('-10 day') + rand(86400, 864000),
                    'update_time' => strtotime('-10 day') + rand(86400, 864000),
                ],[
                    'goods_id' => rand(1,10),
                    'goods_sku' => 'GS' . substr(md5(time()), 0, 8) . rand(100,999),
                    'order_id' => rand(1, 20),
                    'number' => rand(1, 10),
                    'json' => '{}',
                    'create_time' => strtotime('-10 day') + rand(86400, 864000),
                    'update_time' => strtotime('-10 day') + rand(86400, 864000),
                ],[
                    'goods_id' => rand(1,10),
                    'goods_sku' => 'GS' . substr(md5(time()), 0, 8) . rand(100,999),
                    'order_id' => rand(1, 20),
                    'number' => rand(1, 10),
                    'json' => '{}',
                    'create_time' => strtotime('-10 day') + rand(86400, 864000),
                    'update_time' => strtotime('-10 day') + rand(86400, 864000),
                ],[
                    'goods_id' => rand(1,10),
                    'goods_sku' => 'GS' . substr(md5(time()), 0, 8) . rand(100,999),
                    'order_id' => rand(1, 20),
                    'number' => rand(1, 10),
                    'json' => '{}',
                    'create_time' => strtotime('-10 day') + rand(86400, 864000),
                    'update_time' => strtotime('-10 day') + rand(86400, 864000),
                ],[
                    'goods_id' => rand(1,10),
                    'goods_sku' => 'GS' . substr(md5(time()), 0, 8) . rand(100,999),
                    'order_id' => rand(1, 20),
                    'number' => rand(1, 10),
                    'json' => '{}',
                    'create_time' => strtotime('-10 day') + rand(86400, 864000),
                    'update_time' => strtotime('-10 day') + rand(86400, 864000),
                ],[
                    'goods_id' => rand(1,10),
                    'goods_sku' => 'GS' . substr(md5(time()), 0, 8) . rand(100,999),
                    'order_id' => rand(1, 20),
                    'number' => rand(1, 10),
                    'json' => '{}',
                    'create_time' => strtotime('-10 day') + rand(86400, 864000),
                    'update_time' => strtotime('-10 day') + rand(86400, 864000),
                ],[
                    'goods_id' => rand(1,10),
                    'goods_sku' => 'GS' . substr(md5(time()), 0, 8) . rand(100,999),
                    'order_id' => rand(1, 20),
                    'number' => rand(1, 10),
                    'json' => '{}',
                    'create_time' => strtotime('-10 day') + rand(86400, 864000),
                    'update_time' => strtotime('-10 day') + rand(86400, 864000),
                ],[
                    'goods_id' => rand(1,10),
                    'goods_sku' => 'GS' . substr(md5(time()), 0, 8) . rand(100,999),
                    'order_id' => rand(1, 20),
                    'number' => rand(1, 10),
                    'json' => '{}',
                    'create_time' => strtotime('-10 day') + rand(86400, 864000),
                    'update_time' => strtotime('-10 day') + rand(86400, 864000),
                ],[
                    'goods_id' => rand(1,10),
                    'goods_sku' => 'GS' . substr(md5(time()), 0, 8) . rand(100,999),
                    'order_id' => rand(1, 20),
                    'number' => rand(1, 10),
                    'json' => '{}',
                    'create_time' => strtotime('-10 day') + rand(86400, 864000),
                    'update_time' => strtotime('-10 day') + rand(86400, 864000),
                ],[
                    'goods_id' => rand(1,10),
                    'goods_sku' => 'GS' . substr(md5(time()), 0, 8) . rand(100,999),
                    'order_id' => rand(1, 20),
                    'number' => rand(1, 10),
                    'json' => '{}',
                    'create_time' => strtotime('-10 day') + rand(86400, 864000),
                    'update_time' => strtotime('-10 day') + rand(86400, 864000),
                ],[
                    'goods_id' => rand(1,10),
                    'goods_sku' => 'GS' . substr(md5(time()), 0, 8) . rand(100,999),
                    'order_id' => rand(1, 20),
                    'number' => rand(1, 10),
                    'json' => '{}',
                    'create_time' => strtotime('-10 day') + rand(86400, 864000),
                    'update_time' => strtotime('-10 day') + rand(86400, 864000),
                ],[
                    'goods_id' => rand(1,10),
                    'goods_sku' => 'GS' . substr(md5(time()), 0, 8) . rand(100,999),
                    'order_id' => rand(1, 20),
                    'number' => rand(1, 10),
                    'json' => '{}',
                    'create_time' => strtotime('-10 day') + rand(86400, 864000),
                    'update_time' => strtotime('-10 day') + rand(86400, 864000),
                ],[
                    'goods_id' => rand(1,10),
                    'goods_sku' => 'GS' . substr(md5(time()), 0, 8) . rand(100,999),
                    'order_id' => rand(1, 20),
                    'number' => rand(1, 10),
                    'json' => '{}',
                    'create_time' => strtotime('-10 day') + rand(86400, 864000),
                    'update_time' => strtotime('-10 day') + rand(86400, 864000),
                ],[
                    'goods_id' => rand(1,10),
                    'goods_sku' => 'GS' . substr(md5(time()), 0, 8) . rand(100,999),
                    'order_id' => rand(1, 20),
                    'number' => rand(1, 10),
                    'json' => '{}',
                    'create_time' => strtotime('-10 day') + rand(86400, 864000),
                    'update_time' => strtotime('-10 day') + rand(86400, 864000),
                ],[
                    'goods_id' => rand(1,10),
                    'goods_sku' => 'GS' . substr(md5(time()), 0, 8) . rand(100,999),
                    'order_id' => rand(1, 20),
                    'number' => rand(1, 10),
                    'json' => '{}',
                    'create_time' => strtotime('-10 day') + rand(86400, 864000),
                    'update_time' => strtotime('-10 day') + rand(86400, 864000),
                ],[
                    'goods_id' => rand(1,10),
                    'goods_sku' => 'GS' . substr(md5(time()), 0, 8) . rand(100,999),
                    'order_id' => rand(1, 20),
                    'number' => rand(1, 10),
                    'json' => '{}',
                    'create_time' => strtotime('-10 day') + rand(86400, 864000),
                    'update_time' => strtotime('-10 day') + rand(86400, 864000),
                ],[
                    'goods_id' => rand(1,10),
                    'goods_sku' => 'GS' . substr(md5(time()), 0, 8) . rand(100,999),
                    'order_id' => rand(1, 20),
                    'number' => rand(1, 10),
                    'json' => '{}',
                    'create_time' => strtotime('-10 day') + rand(86400, 864000),
                    'update_time' => strtotime('-10 day') + rand(86400, 864000),
                ],[
                    'goods_id' => rand(1,10),
                    'goods_sku' => 'GS' . substr(md5(time()), 0, 8) . rand(100,999),
                    'order_id' => rand(1, 20),
                    'number' => rand(1, 10),
                    'json' => '{}',
                    'create_time' => strtotime('-10 day') + rand(86400, 864000),
                    'update_time' => strtotime('-10 day') + rand(86400, 864000),
                ],[
                    'goods_id' => rand(1,10),
                    'goods_sku' => 'GS' . substr(md5(time()), 0, 8) . rand(100,999),
                    'order_id' => rand(1, 20),
                    'number' => rand(1, 10),
                    'json' => '{}',
                    'create_time' => strtotime('-10 day') + rand(86400, 864000),
                    'update_time' => strtotime('-10 day') + rand(86400, 864000),
                ],[
                    'goods_id' => rand(1,10),
                    'goods_sku' => 'GS' . substr(md5(time()), 0, 8) . rand(100,999),
                    'order_id' => rand(1, 20),
                    'number' => rand(1, 10),
                    'json' => '{}',
                    'create_time' => strtotime('-10 day') + rand(86400, 864000),
                    'update_time' => strtotime('-10 day') + rand(86400, 864000),
                ],[
                    'goods_id' => rand(1,10),
                    'goods_sku' => 'GS' . substr(md5(time()), 0, 8) . rand(100,999),
                    'order_id' => rand(1, 20),
                    'number' => rand(1, 10),
                    'json' => '{}',
                    'create_time' => strtotime('-10 day') + rand(86400, 864000),
                    'update_time' => strtotime('-10 day') + rand(86400, 864000),
                ],[
                    'goods_id' => rand(1,10),
                    'goods_sku' => 'GS' . substr(md5(time()), 0, 8) . rand(100,999),
                    'order_id' => rand(1, 20),
                    'number' => rand(1, 10),
                    'json' => '{}',
                    'create_time' => strtotime('-10 day') + rand(86400, 864000),
                    'update_time' => strtotime('-10 day') + rand(86400, 864000),
                ],[
                    'goods_id' => rand(1,10),
                    'goods_sku' => 'GS' . substr(md5(time()), 0, 8) . rand(100,999),
                    'order_id' => rand(1, 20),
                    'number' => rand(1, 10),
                    'json' => '{}',
                    'create_time' => strtotime('-10 day') + rand(86400, 864000),
                    'update_time' => strtotime('-10 day') + rand(86400, 864000),
                ],[
                    'goods_id' => rand(1,10),
                    'goods_sku' => 'GS' . substr(md5(time()), 0, 8) . rand(100,999),
                    'order_id' => rand(1, 20),
                    'number' => rand(1, 10),
                    'json' => '{}',
                    'create_time' => strtotime('-10 day') + rand(86400, 864000),
                    'update_time' => strtotime('-10 day') + rand(86400, 864000),
                ],[
                    'goods_id' => rand(1,10),
                    'goods_sku' => 'GS' . substr(md5(time()), 0, 8) . rand(100,999),
                    'order_id' => rand(1, 20),
                    'number' => rand(1, 10),
                    'json' => '{}',
                    'create_time' => strtotime('-10 day') + rand(86400, 864000),
                    'update_time' => strtotime('-10 day') + rand(86400, 864000),
                ],[
                    'goods_id' => rand(1,10),
                    'goods_sku' => 'GS' . substr(md5(time()), 0, 8) . rand(100,999),
                    'order_id' => rand(1, 20),
                    'number' => rand(1, 10),
                    'json' => '{}',
                    'create_time' => strtotime('-10 day') + rand(86400, 864000),
                    'update_time' => strtotime('-10 day') + rand(86400, 864000),
                ],[
                    'goods_id' => rand(1,10),
                    'goods_sku' => 'GS' . substr(md5(time()), 0, 8) . rand(100,999),
                    'order_id' => rand(1, 20),
                    'number' => rand(1, 10),
                    'json' => '{}',
                    'create_time' => strtotime('-10 day') + rand(86400, 864000),
                    'update_time' => strtotime('-10 day') + rand(86400, 864000),
                ],[
                    'goods_id' => rand(1,10),
                    'goods_sku' => 'GS' . substr(md5(time()), 0, 8) . rand(100,999),
                    'order_id' => rand(1, 20),
                    'number' => rand(1, 10),
                    'json' => '{}',
                    'create_time' => strtotime('-10 day') + rand(86400, 864000),
                    'update_time' => strtotime('-10 day') + rand(86400, 864000),
                ],[
                    'goods_id' => rand(1,10),
                    'goods_sku' => 'GS' . substr(md5(time()), 0, 8) . rand(100,999),
                    'order_id' => rand(1, 20),
                    'number' => rand(1, 10),
                    'json' => '{}',
                    'create_time' => strtotime('-10 day') + rand(86400, 864000),
                    'update_time' => strtotime('-10 day') + rand(86400, 864000),
                ],[
                    'goods_id' => rand(1,10),
                    'goods_sku' => 'GS' . substr(md5(time()), 0, 8) . rand(100,999),
                    'order_id' => rand(1, 20),
                    'number' => rand(1, 10),
                    'json' => '{}',
                    'create_time' => strtotime('-10 day') + rand(86400, 864000),
                    'update_time' => strtotime('-10 day') + rand(86400, 864000),
                ],[
                    'goods_id' => rand(1,10),
                    'goods_sku' => 'GS' . substr(md5(time()), 0, 8) . rand(100,999),
                    'order_id' => rand(1, 20),
                    'number' => rand(1, 10),
                    'json' => '{}',
                    'create_time' => strtotime('-10 day') + rand(86400, 864000),
                    'update_time' => strtotime('-10 day') + rand(86400, 864000),
                ],[
                    'goods_id' => rand(1,10),
                    'goods_sku' => 'GS' . substr(md5(time()), 0, 8) . rand(100,999),
                    'order_id' => rand(1, 20),
                    'number' => rand(1, 10),
                    'json' => '{}',
                    'create_time' => strtotime('-10 day') + rand(86400, 864000),
                    'update_time' => strtotime('-10 day') + rand(86400, 864000),
                ],[
                    'goods_id' => rand(1,10),
                    'goods_sku' => 'GS' . substr(md5(time()), 0, 8) . rand(100,999),
                    'order_id' => rand(1, 20),
                    'number' => rand(1, 10),
                    'json' => '{}',
                    'create_time' => strtotime('-10 day') + rand(86400, 864000),
                    'update_time' => strtotime('-10 day') + rand(86400, 864000),
                ],[
                    'goods_id' => rand(1,10),
                    'goods_sku' => 'GS' . substr(md5(time()), 0, 8) . rand(100,999),
                    'order_id' => rand(1, 20),
                    'number' => rand(1, 10),
                    'json' => '{}',
                    'create_time' => strtotime('-10 day') + rand(86400, 864000),
                    'update_time' => strtotime('-10 day') + rand(86400, 864000),
                ],[
                    'goods_id' => rand(1,10),
                    'goods_sku' => 'GS' . substr(md5(time()), 0, 8) . rand(100,999),
                    'order_id' => rand(1, 20),
                    'number' => rand(1, 10),
                    'json' => '{}',
                    'create_time' => strtotime('-10 day') + rand(86400, 864000),
                    'update_time' => strtotime('-10 day') + rand(86400, 864000),
                ],[
                    'goods_id' => rand(1,10),
                    'goods_sku' => 'GS' . substr(md5(time()), 0, 8) . rand(100,999),
                    'order_id' => rand(1, 20),
                    'number' => rand(1, 10),
                    'json' => '{}',
                    'create_time' => strtotime('-10 day') + rand(86400, 864000),
                    'update_time' => strtotime('-10 day') + rand(86400, 864000),
                ],[
                    'goods_id' => rand(1,10),
                    'goods_sku' => 'GS' . substr(md5(time()), 0, 8) . rand(100,999),
                    'order_id' => rand(1, 20),
                    'number' => rand(1, 10),
                    'json' => '{}',
                    'create_time' => strtotime('-10 day') + rand(86400, 864000),
                    'update_time' => strtotime('-10 day') + rand(86400, 864000),
                ],[
                    'goods_id' => rand(1,10),
                    'goods_sku' => 'GS' . substr(md5(time()), 0, 8) . rand(100,999),
                    'order_id' => rand(1, 20),
                    'number' => rand(1, 10),
                    'json' => '{}',
                    'create_time' => strtotime('-10 day') + rand(86400, 864000),
                    'update_time' => strtotime('-10 day') + rand(86400, 864000),
                ],
            ]
        );
    }
}
